# Generated by Django 5.0.4 on 2024-04-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='product_detail',
            field=models.CharField(max_length=20),
        ),
    ]
